"""Host-side unit test for the multi-cable USB MIDI configuration descriptor.

``EspUsbDeviceMidi::configurationDescriptor()`` no longer uses TinyUSB's
single-cable ``TUD_MIDI_DESCRIPTOR()`` template; it emits the head, the per-cable
jack descriptors, and the two endpoint blocks itself so the cable count is
variable. That assembly is exactly the kind of thing that fails silently - a host
that reads a wrong ``wTotalLength`` or a duplicated jack ID may still enumerate
the device and just show the wrong number of ports, so a round-trip test on real
hardware would pass while the descriptor is wrong.

As ``tests/unit/ccid_descriptor`` does, the builder is extracted from
``src/EspUsbDevice.cpp`` at test time and compiled on the host together with the
real TinyUSB descriptor macros and enums, so these assertions run against the
shipped code rather than a copy of it.
"""

import re
import subprocess
from pathlib import Path

HERE = Path(__file__).parent
SRC = HERE / ".." / ".." / ".." / "src"

# Enums the TUD_MIDI_* macros expand to. Extracted whole because several members
# take implicit values (AUDIO_SUBCLASS_MIDI_STREAMING is 3 only by position), so
# copying individual values here would silently drift from the headers.
REQUIRED_ENUMS = (
    ("common/tusb_types.h", "tusb_xfer_type_t"),
    ("common/tusb_types.h", "tusb_desc_type_t"),
    ("common/tusb_types.h", "tusb_class_code_t"),
    ("class/audio/audio.h", "audio_subclass_type_t"),
    ("class/audio/audio.h", "audio_function_protocol_code_t"),
    ("class/audio/audio.h", "audio10_cs_ac_interface_subtype_t"),
    ("class/midi/midi.h", "midi_cs_interface_subtype_t"),
    ("class/midi/midi.h", "midi_cs_endpoint_subtype_t"),
    ("class/midi/midi.h", "midi_jack_type_t"),
)

# Little-endian helpers the descriptor macros use.
REQUIRED_MACROS = ("TU_U16_HIGH", "TU_U16_LOW", "U16_TO_U8S_LE")

# The descriptor templates under test. TUD_MIDI_DESCRIPTOR / TUD_MIDI_DESC_LEN are
# no longer used by the builder but are pulled in anyway, so the test can assert the
# default one-cable descriptor is still byte-identical to TinyUSB's template.
REQUIRED_MIDI_MACROS = (
    "TUD_MIDI_DESC_HEAD_LEN",
    "TUD_MIDI_DESC_HEAD",
    "TUD_MIDI_JACKID_IN_EMB",
    "TUD_MIDI_JACKID_IN_EXT",
    "TUD_MIDI_JACKID_OUT_EMB",
    "TUD_MIDI_JACKID_OUT_EXT",
    "TUD_MIDI_DESC_JACK_LEN",
    "TUD_MIDI_DESC_JACK_DESC",
    "TUD_MIDI_DESC_EP_LEN",
    "TUD_MIDI_DESC_EP",
    "TUD_MIDI_DESC_LEN",
    "TUD_MIDI_DESCRIPTOR",
)

# The library's own one-directional jack templates, for cables that exist in only
# one direction. TinyUSB has no equivalent - its jack macro always emits all four.
REQUIRED_LIBRARY_MACROS = (
    "MIDI_ONE_WAY_JACK_LEN",
    "MIDI_DESC_JACK_IN_ONLY",
    "MIDI_DESC_JACK_OUT_ONLY",
)


def _brace_match(text: str, signature: str) -> str:
    """Return signature + body for a function, located by a substring of its
    signature and delimited by brace matching."""
    start = text.index(signature)
    open_brace = text.index("{", start)
    depth = 0
    for i in range(open_brace, len(text)):
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                return text[start : i + 1]
    raise AssertionError(f"unbalanced braces after {signature!r}")


def _extract_enum(source: str, typename: str) -> str:
    """Return the whole `typedef enum { ... } typename;` declaration."""
    end = source.index(f"}} {typename};")
    start = source.rindex("typedef enum", 0, end)
    return source[start : end + len(f"}} {typename};")]


def _extract_define(source: str, name: str) -> str:
    """Return a #define including any backslash-continued lines."""
    match = re.search(r"^#define " + name + r"\b", source, re.M)
    assert match, f"{name} not found"
    lines = []
    for line in source[match.start() :].splitlines():
        lines.append(line)
        if not line.rstrip().endswith("\\"):
            break
    return "\n".join(lines)


def _generate_real_header(dest: Path) -> None:
    parts = [
        "// GENERATED by test_midi_descriptor.py from src/. Do not edit or commit.",
        "#pragma once",
        "#include <stdint.h>",
        "#include <stddef.h>",
        "#include <string.h>",
        "",
    ]

    common = (SRC / "common" / "tusb_common.h").read_text()
    for name in REQUIRED_MACROS:
        parts.append(_extract_define(common, name))
    parts.append("")

    for relative, typename in REQUIRED_ENUMS:
        parts.append(_extract_enum((SRC / relative).read_text(), typename))
    parts.append("")

    usbd = (SRC / "device" / "usbd.h").read_text()
    for name in REQUIRED_MIDI_MACROS:
        parts.append(_extract_define(usbd, name))
    parts.append("")

    source = (SRC / "EspUsbDevice.cpp").read_text()

    for name in REQUIRED_LIBRARY_MACROS:
        parts.append(_extract_define(source, name))
    parts.append("")

    # The methods read the two cable-count members; file-scope variables stand in
    # for them so the bodies can be lifted verbatim.
    parts += [
        "static uint8_t inCableCount_ = 1;",
        "static uint8_t outCableCount_ = 1;",
        "",
        _brace_match(source, "uint16_t EspUsbDeviceMidi::descriptorLength()")
        .replace("EspUsbDeviceMidi::descriptorLength", "midiDescriptorLength")
        .replace("midiDescriptorLength() const", "midiDescriptorLength()"),
        "",
        _brace_match(
            source, "uint16_t EspUsbDeviceMidi::configurationDescriptor("
        ).replace(
            "EspUsbDeviceMidi::configurationDescriptor",
            "midiConfigurationDescriptor",
        ),
        "",
        # configurationDescriptorForSpeed() calls the other two by their member
        # names, so give it those names to call instead of editing its body.
        "static uint16_t descriptorLength() { return midiDescriptorLength(); }",
        "static uint16_t configurationDescriptor(uint8_t *dst, uint8_t itf,",
        "                                        uint8_t ep, uint16_t epSize)",
        "{ return midiConfigurationDescriptor(dst, itf, ep, epSize); }",
        "",
        _brace_match(
            source, "uint16_t EspUsbDeviceMidi::configurationDescriptorForSpeed("
        ).replace(
            "EspUsbDeviceMidi::configurationDescriptorForSpeed",
            "midiConfigurationDescriptorForSpeed",
        ),
        "",
    ]
    dest.write_text("\n".join(parts))


def test_midi_descriptor():
    output = HERE / "output"
    output.mkdir(exist_ok=True)
    _generate_real_header(output / "espusbdevice_midi_real.h")

    binary = output / "midi_descriptor_test"
    compile_result = subprocess.run(
        [
            "g++",
            "-std=c++17",
            "-Wall",
            "-Wextra",
            "-Werror",
            "-I",
            str(output),
            str(HERE / "midi_descriptor_test.cpp"),
            "-o",
            str(binary),
        ],
        capture_output=True,
        text=True,
    )
    assert compile_result.returncode == 0, compile_result.stdout + compile_result.stderr

    run_result = subprocess.run([str(binary)], capture_output=True, text=True)
    assert run_result.returncode == 0, run_result.stdout + run_result.stderr
