def test_loopback_hid_mouse(dut):
    dut.expect_exact("HOST_DEVICE")
    dut.expect_exact("HID_DESC iface=0")
    dut.expect_exact("HID_INPUT iface=0 subclass=1 protocol=2 len=4 data=00 28 00 00")
    dut.expect_exact("MOUSE x=40 y=0 wheel=0 buttons=0 previous=0 moved=1 changed=0")
    dut.expect_exact("MOUSE x=-40 y=0 wheel=0 buttons=0 previous=0 moved=1 changed=0")
    dut.expect_exact("MOUSE x=0 y=40 wheel=0 buttons=0 previous=0 moved=1 changed=0")
    dut.expect_exact("MOUSE x=0 y=-40 wheel=0 buttons=0 previous=0 moved=1 changed=0")
    dut.expect_exact("MOUSE x=0 y=0 wheel=1 buttons=0 previous=0 moved=1 changed=0")
    dut.expect_exact("buttons=4 previous=0 moved=0 changed=1")
    dut.expect_exact("buttons=0 previous=4 moved=0 changed=1")
    dut.expect_exact("buttons=1 previous=0 moved=0 changed=1")
    dut.expect_exact("buttons=0 previous=1 moved=0 changed=1")
    dut.expect_exact("buttons=2 previous=0 moved=0 changed=1")
    dut.expect_exact("buttons=0 previous=2 moved=0 changed=1")
    dut.expect_exact("buttons=8 previous=0 moved=0 changed=1")
    dut.expect_exact("buttons=0 previous=8 moved=0 changed=1")
    dut.expect_exact("buttons=16 previous=0 moved=0 changed=1")
    dut.expect_exact("buttons=0 previous=16 moved=0 changed=1")
    dut.expect_exact("TEST_END ok")
    assert dut.expect_exact(["OK", "NG"]) == b"OK"
