// Host-side unit tests for EspUsbDeviceNkroKeyboardReport, the NKRO held-key
// state that EspUsbDeviceHidKeyboard::sendReport() takes and heldState()
// returns.
//
// The struct is header-only, so this file compiles the real definition rather
// than a copy: test_nkro_report.py extracts it verbatim from src/EspUsbDevice.h
// into "espusbdevice_nkro_real.h" in the build output directory. Same approach
// as tests/unit/keymap - the checks must not be able to drift away from the
// shipped struct.
//
// What is covered here is everything that does not need a USB bus: the bitmap
// layout, the 0xE0-0xE7 modifier routing, and the MaxBitmapUsage boundary. The
// boot-protocol fold-down, the "no enableNkro() -> fail" rule and the actual
// bytes on the wire live in EspUsbDeviceHidKeyboard, which cannot be compiled on
// the host; those are covered on hardware by tests/peer/hid_keyboard_nkro.

#include <cstdint>
#include <cstddef>
#include <cstdio>

// Generated by test_nkro_report.py from src/EspUsbDevice.h.
#include "espusbdevice_nkro_real.h"

namespace
{
int failures = 0;

void check(const char *name, bool condition)
{
  if (!condition)
  {
    std::printf("FAIL: %s\n", name);
    failures++;
  }
}

// Number of set bits across the whole bitmap, so a test can assert that a
// single press() touched exactly one bit and nothing else.
unsigned bitsSet(const EspUsbDeviceNkroKeyboardReport &report)
{
  unsigned count = 0;
  for (size_t index = 0; index < EspUsbDeviceNkroKeyboardReport::BitmapSize; index++)
  {
    for (unsigned bit = 0; bit < 8; bit++)
    {
      if (report.bitmap[index] & (1u << bit))
      {
        count++;
      }
    }
  }
  return count;
}
}  // namespace

int main()
{
  // --- Shape ---
  // 28 bytes covers usages 0x00-0xDF exactly, leaving 0xE0-0xE7 to `modifiers`.
  check("BitmapSize is 28", EspUsbDeviceNkroKeyboardReport::BitmapSize == 28);
  check("MaxBitmapUsage is 0xdf", EspUsbDeviceNkroKeyboardReport::MaxBitmapUsage == 0xdf);
  check("bitmap sizeof matches BitmapSize",
        sizeof(EspUsbDeviceNkroKeyboardReport::bitmap) == EspUsbDeviceNkroKeyboardReport::BitmapSize);

  {
    EspUsbDeviceNkroKeyboardReport report;
    check("default modifiers are clear", report.modifiers == 0);
    check("default bitmap is clear", bitsSet(report) == 0);
    check("default isDown is false", !report.isDown(0x04));
  }

  // --- Bitmap layout ---
  // bit (usage & 7) of byte (usage >> 3). Usage 0x04 ('a') is byte 0, bit 4.
  {
    EspUsbDeviceNkroKeyboardReport report;
    check("press(0x04) accepted", report.press(0x04));
    check("0x04 sets byte 0 bit 4", report.bitmap[0] == 0x10);
    check("press(0x04) sets exactly one bit", bitsSet(report) == 1);
    check("press(0x04) leaves modifiers alone", report.modifiers == 0);
    check("isDown(0x04) after press", report.isDown(0x04));
    // The neighbouring usages share the byte and must not be reported down -
    // this is the mistake that reading the bitmap as a usage array produces.
    check("isDown(0x03) still false", !report.isDown(0x03));
    check("isDown(0x05) still false", !report.isDown(0x05));

    check("release(0x04) accepted", report.release(0x04));
    check("release(0x04) clears the bit", bitsSet(report) == 0);
    check("isDown(0x04) after release", !report.isDown(0x04));
  }

  // Highest and lowest representable usages, and byte/bit arithmetic in between.
  {
    EspUsbDeviceNkroKeyboardReport report;
    check("press(0x00) accepted", report.press(0x00));
    check("0x00 is byte 0 bit 0", report.bitmap[0] == 0x01);
    check("press(0xdf) accepted", report.press(0xdf));
    check("0xdf is byte 27 bit 7", report.bitmap[27] == 0x80);
    check("press(0x87) accepted (International1)", report.press(0x87));
    check("0x87 is byte 16 bit 7", report.bitmap[16] == 0x80);
    check("press(0x90) accepted (LANG1)", report.press(0x90));
    check("0x90 is byte 18 bit 0", report.bitmap[18] == 0x01);
    check("four presses set four bits", bitsSet(report) == 4);
    check("isDown(0x00)", report.isDown(0x00));
    check("isDown(0xdf)", report.isDown(0xdf));
    check("isDown(0x87)", report.isDown(0x87));
    check("isDown(0x90)", report.isDown(0x90));
  }

  // --- More than six keys in one report (the whole point of the type) ---
  {
    EspUsbDeviceNkroKeyboardReport report;
    const uint8_t chord[] = {0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a, 0x0b, 0x0c, 0x0d};
    for (uint8_t usage : chord)
    {
      check("chord press accepted", report.press(usage));
    }
    check("ten keys held at once", bitsSet(report) == 10);
    for (uint8_t usage : chord)
    {
      check("chord key is down", report.isDown(usage));
    }
  }

  // --- Modifier routing (0xE0-0xE7 go to `modifiers`, never the bitmap) ---
  {
    EspUsbDeviceNkroKeyboardReport report;
    check("press(0xe0) accepted (LeftCtrl)", report.press(0xe0));
    check("LeftCtrl is modifiers bit 0", report.modifiers == 0x01);
    check("modifier does not touch the bitmap", bitsSet(report) == 0);
    check("isDown(0xe0) reads modifiers", report.isDown(0xe0));

    check("press(0xe7) accepted (RightGui)", report.press(0xe7));
    check("RightGui is modifiers bit 7", report.modifiers == 0x81);
    check("isDown(0xe7) reads modifiers", report.isDown(0xe7));
    check("isDown(0xe1) still false", !report.isDown(0xe1));

    // Releasing a modifier must actually clear it. The incremental API used to
    // leave modifiers held until releaseAll(); routing through release() is what
    // fixes that, so guard it here.
    check("release(0xe0) accepted", report.release(0xe0));
    check("release(0xe0) clears only that bit", report.modifiers == 0x80);
    check("isDown(0xe0) after release", !report.isDown(0xe0));
  }

  // --- Boundary: 0xE8 and above cannot be represented ---
  // Above the modifier range there is nowhere to put the usage, so press() /
  // release() report failure instead of silently discarding it (the old private
  // setKeyBit() returned early and said nothing).
  {
    EspUsbDeviceNkroKeyboardReport report;
    check("press(0xe8) rejected", !report.press(0xe8));
    check("press(0xff) rejected", !report.press(0xff));
    check("release(0xe8) rejected", !report.release(0xe8));
    check("release(0xff) rejected", !report.release(0xff));
    check("rejected press changes nothing", bitsSet(report) == 0 && report.modifiers == 0);
    check("isDown(0xe8) is false", !report.isDown(0xe8));
    check("isDown(0xff) is false", !report.isDown(0xff));
  }

  // --- clear() ---
  {
    EspUsbDeviceNkroKeyboardReport report;
    report.press(0x04);
    report.press(0xdf);
    report.press(0xe1);
    check("state is populated before clear", bitsSet(report) == 2 && report.modifiers != 0);
    report.clear();
    check("clear() empties the bitmap", bitsSet(report) == 0);
    check("clear() empties modifiers", report.modifiers == 0);
  }

  // --- Copy semantics ---
  // sendReport() assigns the caller's report into the internal state and
  // heldState() hands the state back, so plain value copies must carry
  // everything. A trivially copyable aggregate is also what lets the send path
  // memcpy() the bitmap straight onto the wire.
  {
    EspUsbDeviceNkroKeyboardReport source;
    source.press(0x04);
    source.press(0x90);
    source.press(0xe2);
    EspUsbDeviceNkroKeyboardReport copy = source;
    check("copy keeps the bitmap", bitsSet(copy) == 2);
    check("copy keeps modifiers", copy.modifiers == source.modifiers);
    check("copy isDown(0x04)", copy.isDown(0x04));
    check("copy isDown(0x90)", copy.isDown(0x90));
    check("copy isDown(0xe2)", copy.isDown(0xe2));
    copy.release(0x04);
    check("copy is independent of the source", source.isDown(0x04));
  }

  if (failures != 0)
  {
    std::printf("%d check(s) failed\n", failures);
    return 1;
  }
  std::puts("OK - all NKRO report checks passed");
  return 0;
}
