"""Host-side unit test for the NKRO held-key state struct.

``EspUsbDeviceNkroKeyboardReport`` (``src/EspUsbDevice.h``) is header-only, but
the header as a whole pulls in ``Arduino.h`` and the ESP USB device stack and so
cannot be compiled on the host. Rather than copy the struct into the test (which
would let the two drift apart), this test extracts the real definition from the
header at run time, writes it to ``output/espusbdevice_nkro_real.h`` and compiles
that together with ``nkro_report_test.cpp``. The assertions therefore run against
the shipped struct - if a bit-twiddling or boundary rule changes, this test sees
it.

Same technique as ``tests/unit/keymap``. No board required.
"""

import re
import subprocess
from pathlib import Path

HERE = Path(__file__).parent
SRC = HERE / ".." / ".." / ".." / "src"


def _generate_real_header(dest: Path) -> None:
    device_h = (SRC / "EspUsbDevice.h").read_text()

    struct_match = re.search(
        r"struct EspUsbDeviceNkroKeyboardReport\s*\{.*?\n\};", device_h, re.S
    )
    assert struct_match, (
        "EspUsbDeviceNkroKeyboardReport not found in EspUsbDevice.h - "
        "was the struct renamed or reformatted?"
    )
    struct_text = struct_match.group(0)

    # The struct must stay self-contained (plain integer members and inline
    # bit operations) for this host build to be meaningful. Anything reaching
    # into the Arduino / TinyUSB world would compile here only by accident.
    for forbidden in ("Arduino", "tud_", "std::function", "String"):
        assert forbidden not in struct_text, (
            f"EspUsbDeviceNkroKeyboardReport now references {forbidden!r}; "
            "the host-side extraction in this test no longer holds"
        )

    dest.write_text(
        "\n".join(
            [
                "// GENERATED by test_nkro_report.py from src/EspUsbDevice.h.",
                "// Do not edit; do not commit.",
                "#pragma once",
                "#include <stdint.h>",
                "#include <stddef.h>",
                "",
                struct_text,
                "",
            ]
        )
    )


def test_nkro_report_struct():
    output = HERE / "output"
    output.mkdir(exist_ok=True)
    _generate_real_header(output / "espusbdevice_nkro_real.h")

    binary = output / "nkro_report_test"
    compile_result = subprocess.run(
        [
            "g++",
            "-std=c++17",
            # Match the Xtensa toolchain where plain char is unsigned.
            "-funsigned-char",
            "-Wall",
            "-Wextra",
            "-Werror",
            "-I", str(output),          # espusbdevice_nkro_real.h
            str(HERE / "nkro_report_test.cpp"),
            "-o", str(binary),
        ],
        capture_output=True,
        text=True,
    )
    assert compile_result.returncode == 0, compile_result.stdout + compile_result.stderr

    run_result = subprocess.run([str(binary)], capture_output=True, text=True)
    assert run_result.returncode == 0, run_result.stdout + run_result.stderr
