#!/usr/bin/env python3
"""Generate the MJPEG test frames this sketch streams, as a C array.

MJPEG is the format that matters on a full-speed part - uncompressed QVGA at
any usable rate does not fit in 1 MB/s - but a device cannot prove it streams
MJPEG with one still image: a host showing the same picture forever looks the
same as a host showing a stuck frame. So this writes a short loop of frames
with a moving element, encoded once here rather than on the ESP32, which has
no JPEG encoder in this library.

    uv run --with pillow python make_frames.py

Regenerate and commit `frames.h` when the size, count or content changes; the
sketch includes it directly so the test needs no build step of its own.
"""

from __future__ import annotations

from pathlib import Path

from PIL import Image, ImageDraw

WIDTH = 320
HEIGHT = 240
FRAMES = 16
QUALITY = 70
BARS = [
    (192, 192, 192), (192, 192, 0), (0, 192, 192), (0, 192, 0),
    (192, 0, 192), (192, 0, 0), (0, 0, 192), (16, 16, 16),
]


def frame(index: int) -> bytes:
    image = Image.new("RGB", (WIDTH, HEIGHT))
    draw = ImageDraw.Draw(image)
    # Colour bars: a still background that makes a torn or reordered frame
    # obvious, because the bar edges are vertical and hard.
    bar = WIDTH / len(BARS)
    for i, colour in enumerate(BARS):
        draw.rectangle([i * bar, 0, (i + 1) * bar - 1, HEIGHT * 3 // 4], fill=colour)
    # The moving part: a block that steps across the bottom, one cell per frame.
    # Position encodes the frame number, so a viewer can see the stream advance
    # and a stall shows as the block stopping.
    cell = WIDTH // FRAMES
    x = index * cell
    draw.rectangle([x, HEIGHT * 3 // 4, x + cell - 1, HEIGHT - 1], fill=(255, 255, 255))
    draw.text((4, HEIGHT - 16), f"{index:02d}", fill=(0, 0, 0))
    from io import BytesIO

    buffer = BytesIO()
    image.save(buffer, format="JPEG", quality=QUALITY)
    return buffer.getvalue()


def main() -> int:
    frames = [frame(i) for i in range(FRAMES)]
    largest = max(len(f) for f in frames)
    out = [
        "// Generated by make_frames.py - do not edit.",
        "//",
        f"// {FRAMES} MJPEG frames, {WIDTH}x{HEIGHT}, quality {QUALITY}.",
        "#pragma once",
        "",
        f"#define UVC_FRAME_WIDTH {WIDTH}",
        f"#define UVC_FRAME_HEIGHT {HEIGHT}",
        f"#define UVC_FRAME_COUNT {FRAMES}",
        f"#define UVC_FRAME_MAX_BYTES {largest}",
        "",
    ]
    for i, data in enumerate(frames):
        out.append(f"static const uint8_t kFrame{i:02d}[] = {{")
        for start in range(0, len(data), 16):
            chunk = data[start:start + 16]
            out.append("    " + "".join(f"0x{b:02x}, " for b in chunk).rstrip())
        out.append("};")
    out.append("")
    out.append("static const uint8_t *const kFrames[UVC_FRAME_COUNT] = {")
    out.append("    " + ", ".join(f"kFrame{i:02d}" for i in range(FRAMES)))
    out.append("};")
    out.append("static const uint16_t kFrameSizes[UVC_FRAME_COUNT] = {")
    out.append("    " + ", ".join(str(len(f)) for f in frames))
    out.append("};")
    out.append("")
    Path("frames.h").write_text("\n".join(out), encoding="utf-8")
    total = sum(len(f) for f in frames)
    print(f"frames.h: {FRAMES} frames, {total} bytes total, largest {largest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
