def test_loopback_hid_keyboard(dut):
    dut.expect_exact("TEST_BEGIN loopback_hid_keyboard")
    dut.expect_exact("HOST_READY fs")
    dut.expect_exact("DEVICE_READY fs")
    dut.expect_exact("HOST_DEVICE")
    dut.expect_exact("hello, keyboard")
    dut.expect_exact("LED_TX 1")
    dut.expect_exact("LED numlock=1 capslock=0 scrolllock=0")
    dut.expect_exact("LED_TX 1")
    dut.expect_exact("LED numlock=0 capslock=1 scrolllock=0")
    dut.expect_exact("LED_TX 1")
    dut.expect_exact("LED numlock=0 capslock=0 scrolllock=1")
    dut.expect_exact("LED_TX 1")
    dut.expect_exact("LED numlock=0 capslock=0 scrolllock=0")
    dut.expect_exact("TEST_END ok")
    assert dut.expect_exact(["OK", "NG"]) == b"OK"
