"""Host-side unit test for the CCID interface / class descriptor bytes.

``EspUsbDeviceCcid::configurationDescriptor()`` is the one part of the CCID
function a host reads before anything else works: get a field wrong and the host
either refuses the reader or drives it with the wrong exchange level. The method
itself is pure byte assembly with no Arduino or TinyUSB dependency, so - as
``tests/unit/keymap`` does for the keymap reverse lookup - it is extracted from
``src/EspUsbDeviceCcid.cpp`` at test time and compiled on the host. The
assertions therefore run against the production code, not a copy of it.
"""

import re
import subprocess
from pathlib import Path

HERE = Path(__file__).parent
SRC = HERE / ".." / ".." / ".." / "src"

# Constants the extracted method refers to. Named explicitly so that renaming one
# in the library fails this test loudly instead of silently dropping a check.
REQUIRED_CONSTANTS = (
    "USB_DESC_INTERFACE",
    "USB_DESC_ENDPOINT",
    "USB_DESC_CCID",
    "USB_CLASS_SMART_CARD",
    "USB_ENDPOINT_ATTR_BULK",
    "USB_ENDPOINT_ATTR_INTERRUPT",
    "CCID_HEADER_SIZE",
    "CCID_BULK_ENDPOINT_SIZE",
    "CCID_INTERRUPT_ENDPOINT_SIZE",
    "CCID_INTERRUPT_INTERVAL_MS",
)


def _brace_match(text: str, signature: str) -> str:
    """Return signature + body for a function, located by a substring of its
    signature and delimited by brace matching."""
    start = text.index(signature)
    open_brace = text.index("{", start)
    depth = 0
    for i in range(open_brace, len(text)):
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                return text[start : i + 1]
    raise AssertionError(f"unbalanced braces after {signature!r}")


def _generate_real_header(dest: Path) -> None:
    source = (SRC / "EspUsbDeviceCcid.cpp").read_text()

    constants = []
    for name in REQUIRED_CONSTANTS:
        match = re.search(
            r"^static constexpr \w+ " + name + r" = [^;]+;", source, re.M
        )
        assert match, f"{name} not found in EspUsbDeviceCcid.cpp"
        constants.append(match.group(0))

    helpers = [
        _brace_match(source, "static void ccidWrite16("),
        _brace_match(source, "static void ccidWrite32("),
    ]

    method = _brace_match(source, "uint16_t EspUsbDeviceCcid::configurationDescriptor(")
    method = method.replace(
        "EspUsbDeviceCcid::configurationDescriptor", "ccidConfigurationDescriptor"
    )

    parts = [
        "// GENERATED by test_ccid_descriptor.py from src/EspUsbDeviceCcid.cpp.",
        "// Do not edit; do not commit.",
        "#pragma once",
        "#include <stdint.h>",
        "#include <stddef.h>",
        "#include <string.h>",
        "",
        *constants,
        "",
        *helpers,
        "",
        method,
        "",
    ]
    dest.write_text("\n".join(parts))


def test_ccid_descriptor():
    output = HERE / "output"
    output.mkdir(exist_ok=True)
    _generate_real_header(output / "espusbdevice_ccid_real.h")

    binary = output / "ccid_descriptor_test"
    compile_result = subprocess.run(
        [
            "g++",
            "-std=c++17",
            "-Wall",
            "-Wextra",
            "-Werror",
            "-I",
            str(output),
            str(HERE / "ccid_descriptor_test.cpp"),
            "-o",
            str(binary),
        ],
        capture_output=True,
        text=True,
    )
    assert compile_result.returncode == 0, compile_result.stdout + compile_result.stderr

    run_result = subprocess.run([str(binary)], capture_output=True, text=True)
    assert run_result.returncode == 0, run_result.stdout + run_result.stderr
