// Host-side unit tests for the character -> HID usage+modifier reverse lookup.
//
// EspUsbDevice types text by reverse-looking-up each character in the same
// keymap tables that EspUsbHost uses in the forward direction. This file is
// compiled and run on the host with g++ (no board required) by test_keymap.py.
// The layout enum, the MOD_* constants, the keymap include list, and the pure
// reverse-lookup function (espUsbDeviceAsciiToUsage) are extracted verbatim from
// the real library sources at test time and written to
// "espusbdevice_keymap_real.h" in the build output directory, so these checks
// exercise the actual production tables and conversion logic - not a copy.
//
// Note: the en_US table is a zero stub on the host build (its real values come
// from TinyUSB's HID_KEYCODE_TO_ASCII macro), so en_US character values are not
// asserted here - the assertions cover de_DE / fr_FR / pt_BR / it_IT etc. which
// carry real data.

#include <cstdint>
#include <cstddef>
#include <cstdio>

// Generated by test_keymap.py: enum + MOD_* constants + keymap tables +
// reverse-lookup function, all extracted from src/EspUsbDevice.h and
// src/EspUsbDevice.cpp.
#include "espusbdevice_keymap_real.h"

namespace
{
int failures = 0;
constexpr uint8_t Shift = 0x02;   // ESP_USB_DEVICE_MOD_LEFT_SHIFT
constexpr uint8_t AltGr = 0x40;   // ESP_USB_DEVICE_MOD_RIGHT_ALT

// Assert that character `c` reverse-maps to `expectedUsage` with `expectedMod`.
void check(const char *name, char c, EspUsbDeviceKeyboardLayout layout,
          bool expectedFound, unsigned expectedUsage, unsigned expectedMod)
{
  uint8_t usage = 0xff;
  uint8_t modifiers = 0xff;
  bool found = espUsbDeviceAsciiToUsage(c, layout, usage, modifiers);
  if (found != expectedFound)
  {
    std::printf("FAIL %-46s found=%d expected found=%d\n", name, found, expectedFound);
    ++failures;
    return;
  }
  if (!expectedFound)
  {
    return; // usage/modifiers undefined-ish when not found; nothing more to check
  }
  if (usage != expectedUsage || modifiers != expectedMod)
  {
    std::printf("FAIL %-46s got usage=0x%02x mod=0x%02x expected usage=0x%02x mod=0x%02x\n",
                name, usage, modifiers, expectedUsage, expectedMod);
    ++failures;
  }
}
} // namespace

int main()
{
  const auto DaDk = ESP_USB_DEVICE_KEYBOARD_LAYOUT_DA_DK;
  const auto DeDe = ESP_USB_DEVICE_KEYBOARD_LAYOUT_DE_DE;
  const auto EsEs = ESP_USB_DEVICE_KEYBOARD_LAYOUT_ES_ES;
  const auto FrFr = ESP_USB_DEVICE_KEYBOARD_LAYOUT_FR_FR;
  const auto ItIt = ESP_USB_DEVICE_KEYBOARD_LAYOUT_IT_IT;
  const auto NlNl = ESP_USB_DEVICE_KEYBOARD_LAYOUT_NL_NL;
  const auto PtBr = ESP_USB_DEVICE_KEYBOARD_LAYOUT_PT_BR;
  const auto SvSe = ESP_USB_DEVICE_KEYBOARD_LAYOUT_SV_SE;

  // --- Base / Shift level (must be unchanged by the uint16_t[4] migration) ---
  // de_DE letters and the y/z swap.
  check("deDE a -> base 0x04", 'a', DeDe, true, 0x04, 0);
  check("deDE A -> shift 0x04", 'A', DeDe, true, 0x04, Shift);
  check("deDE z -> base 0x1c (QWERTZ swap)", 'z', DeDe, true, 0x1c, 0);
  check("deDE y -> base 0x1d (QWERTZ swap)", 'y', DeDe, true, 0x1d, 0);
  check("deDE 1 -> base 0x1e", '1', DeDe, true, 0x1e, 0);
  // de_DE '/' is Shift+7 (usage 0x24); base/Shift must win over any AltGr entry.
  check("deDE / -> shift 0x24", '/', DeDe, true, 0x24, Shift);
  // Latin-1 base/shift letters (eszett, u-umlaut).
  check("deDE eszett -> base 0x2d", '\xdf', DeDe, true, 0x2d, 0);
  check("deDE u-umlaut -> base 0x2f", '\xfc', DeDe, true, 0x2f, 0);
  check("deDE U-umlaut -> shift 0x2f", '\xdc', DeDe, true, 0x2f, Shift);

  // fr_FR AZERTY positions and shifted digits.
  check("frFR a-position -> q at 0x04", 'q', FrFr, true, 0x04, 0);
  check("frFR shift 2 -> 0x1f", '2', FrFr, true, 0x1f, Shift);

  // --- AltGr (Right Alt) fallback level ---
  // de_DE (Windows KBDGR / DIN 2137 T1).
  check("deDE @ -> AltGr Q 0x14", '@', DeDe, true, 0x14, AltGr);
  check("deDE { -> AltGr 7 0x24", '{', DeDe, true, 0x24, AltGr);
  check("deDE [ -> AltGr 8 0x25", '[', DeDe, true, 0x25, AltGr);
  check("deDE ] -> AltGr 9 0x26", ']', DeDe, true, 0x26, AltGr);
  check("deDE } -> AltGr 0 0x27", '}', DeDe, true, 0x27, AltGr);
  check("deDE backslash -> AltGr eszett 0x2d", '\\', DeDe, true, 0x2d, AltGr);
  check("deDE ~ -> AltGr + 0x30", '~', DeDe, true, 0x30, AltGr);
  check("deDE | -> AltGr < 0x64", '|', DeDe, true, 0x64, AltGr);
  check("deDE micro -> AltGr m 0x10", '\xb5', DeDe, true, 0x10, AltGr);

  // fr_FR AltGr layer.
  check("frFR @ -> AltGr 0 0x27", '@', FrFr, true, 0x27, AltGr);
  check("frFR # -> AltGr 3 0x20", '#', FrFr, true, 0x20, AltGr);
  check("frFR { -> AltGr 4 0x21", '{', FrFr, true, 0x21, AltGr);
  check("frFR [ -> AltGr 5 0x22", '[', FrFr, true, 0x22, AltGr);

  // es_ES AltGr layer.
  check("esES @ -> AltGr 2 0x1f", '@', EsEs, true, 0x1f, AltGr);
  check("esES # -> AltGr 3 0x20", '#', EsEs, true, 0x20, AltGr);

  // it_IT: [ ] are AltGr (level 3); { } are AltGr+Shift (level 4).
  check("itIT @ -> AltGr o-grave 0x33", '@', ItIt, true, 0x33, AltGr);
  check("itIT [ -> AltGr e-grave 0x2f", '[', ItIt, true, 0x2f, AltGr);
  check("itIT { -> AltGr+Shift e-grave 0x2f", '{', ItIt, true, 0x2f, AltGr | Shift);
  check("itIT } -> AltGr+Shift + 0x30", '}', ItIt, true, 0x30, AltGr | Shift);

  // Nordic programmer AltGr row (da_DK / sv_SE share 2@ 7{ 8[ 9] 0}).
  check("daDK @ -> AltGr 2 0x1f", '@', DaDk, true, 0x1f, AltGr);
  check("daDK { -> AltGr 7 0x24", '{', DaDk, true, 0x24, AltGr);
  check("daDK backslash -> AltGr < 0x64", '\\', DaDk, true, 0x64, AltGr);
  check("svSE backslash -> AltGr + 0x2d", '\\', SvSe, true, 0x2d, AltGr);
  check("svSE | -> AltGr < 0x64", '|', SvSe, true, 0x64, AltGr);

  // nl_NL AltGr layer.
  check("nlNL { -> AltGr 8 0x25", '{', NlNl, true, 0x25, AltGr);
  check("nlNL } -> AltGr 9 0x26", '}', NlNl, true, 0x26, AltGr);

  // --- pt_BR: the 0x90 tableSize fix ---
  // '/' and '?' live on International1 (usage 0x87), which is only reachable
  // when pt_BR scans the extended 0x90-entry table. If tableSize were 128 the
  // base/Shift scan would miss 0x87 and '/' would incorrectly fall back to
  // AltGr+Q (usage 0x14). So these two assertions are the regression guard for
  // KEYMAP_FIX_REQUEST.ja.md sections 1 and 3.
  check("ptBR / -> International1 base 0x87", '/', PtBr, true, 0x87, 0);
  check("ptBR ? -> International1 shift 0x87", '?', PtBr, true, 0x87, Shift);
  // The slash key (0x38) stays ';' / ':' on ABNT2.
  check("ptBR ; -> base 0x38", ';', PtBr, true, 0x38, 0);
  check("ptBR : -> shift 0x38", ':', PtBr, true, 0x38, Shift);
  // pt_BR cedilla is a base/shift Latin-1 letter at 0x33.
  check("ptBR cedilla -> base 0x33", '\xe7', PtBr, true, 0x33, 0);
  check("ptBR C-cedilla -> shift 0x33", '\xc7', PtBr, true, 0x33, Shift);

  // --- Not-found path ---
  // A character that appears in no column of the layout must return false.
  // ('\x01' / SOH is never a keymap value; printable-only tables plus the few
  // control chars \r \x1b \b \t and space are the only non-zero base entries.)
  check("deDE SOH not found", '\x01', DeDe, /*found=*/false, 0, 0);
  // EUR (U+20AC = AltGr+E) is not representable as a single byte, so it can
  // never be passed to this char-based API - see KEYMAP_FIX_REQUEST.ja.md sec5.
  // Nothing to assert directly; documented here for the reader.

  if (failures != 0)
  {
    std::printf("%d check(s) failed\n", failures);
    return 1;
  }
  std::puts("OK - all keymap reverse-lookup checks passed");
  return 0;
}
