"""Host-side unit test for the keymap tables and the char->usage reverse lookup.

The reverse-lookup logic lives in ``src/EspUsbDevice.cpp``, which pulls in
``Arduino.h`` and the ESP USB device stack and therefore cannot be compiled on
the host directly. Rather than duplicate the logic (which would let the test and
the library drift apart), this test extracts the pieces it needs straight from
the real sources at run time:

* the ``EspUsbDeviceKeyboardLayout`` enum and the ``ESP_USB_DEVICE_MOD_*``
  constants from ``src/EspUsbDevice.h``
* the ``#include "keymap/..."`` list and the pure ``espUsbDeviceAsciiToUsage``
  function from ``src/EspUsbDevice.cpp``

These are concatenated into ``output/espusbdevice_keymap_real.h`` and compiled
together with ``keymap_test.cpp``. The assertions thus run against the actual
production tables and conversion code.

The keymap tables (``src/keymap/*.h``) are byte-identical to EspUsbHost's, whose
forward-direction values are covered by that library's own keymap unit test;
this test covers the EspUsbDevice-specific reverse direction.
"""

import re
import subprocess
from pathlib import Path

HERE = Path(__file__).parent
SRC = HERE / ".." / ".." / ".." / "src"


def _brace_match(text: str, signature: str) -> str:
    """Return the full definition (signature + body) for a function, located by
    a substring of its signature and delimited by brace matching."""
    start = text.index(signature)
    open_brace = text.index("{", start)
    depth = 0
    for i in range(open_brace, len(text)):
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                return text[start : i + 1]
    raise AssertionError(f"unbalanced braces after {signature!r}")


def _generate_real_header(dest: Path) -> None:
    device_h = (SRC / "EspUsbDevice.h").read_text()
    device_cpp = (SRC / "EspUsbDevice.cpp").read_text()

    enum_match = re.search(
        r"enum EspUsbDeviceKeyboardLayout\s*:\s*\w+\s*\{.*?\};", device_h, re.S
    )
    assert enum_match, "EspUsbDeviceKeyboardLayout enum not found in EspUsbDevice.h"

    mod_consts = re.findall(
        r"^static constexpr uint8_t ESP_USB_DEVICE_MOD_[A-Z_]+ = 0x[0-9a-fA-F]+;",
        device_h,
        re.M,
    )
    assert mod_consts, "ESP_USB_DEVICE_MOD_* constants not found in EspUsbDevice.h"

    keymap_includes = re.findall(r'^#include "keymap/[^"]+"', device_cpp, re.M)
    assert keymap_includes, "no keymap includes found in EspUsbDevice.cpp"

    reverse_fn = _brace_match(device_cpp, "bool espUsbDeviceAsciiToUsage(")

    parts = [
        "// GENERATED by test_keymap.py from src/EspUsbDevice.h and",
        "// src/EspUsbDevice.cpp. Do not edit; do not commit.",
        "#pragma once",
        "#include <stdint.h>",
        "#include <stddef.h>",
        "",
        enum_match.group(0),
        "",
        *mod_consts,
        "",
        *keymap_includes,
        "",
        reverse_fn,
        "",
    ]
    dest.write_text("\n".join(parts))


def test_keymap_reverse_lookup():
    output = HERE / "output"
    output.mkdir(exist_ok=True)
    _generate_real_header(output / "espusbdevice_keymap_real.h")

    binary = output / "keymap_test"
    compile_result = subprocess.run(
        [
            "g++",
            "-std=c++17",
            # Match the Xtensa toolchain where plain char is unsigned.
            "-funsigned-char",
            "-Wall",
            "-Wextra",
            "-I", str(output),          # espusbdevice_keymap_real.h
            "-I", str(SRC),             # keymap/*.h tables
            "-I", str(HERE / "stub"),   # class/hid/hid.h stub
            str(HERE / "keymap_test.cpp"),
            "-o", str(binary),
        ],
        capture_output=True,
        text=True,
    )
    assert compile_result.returncode == 0, compile_result.stderr

    run_result = subprocess.run([str(binary)], capture_output=True, text=True)
    assert run_result.returncode == 0, run_result.stdout + run_result.stderr
